6 get comments by review
RyanNolan1/BE-NC-Games pull request #6
Opened 2022-11-17 15:17 UTC by RyanNolan1

2022-11-17 15:45 UTC, yangalexyangg requested changes
Looks good but can you please add some error handling. What if there is an invalid id? or the review is not found? Also please test for if the article exists but there is no comments

2022-11-18 11:18 UTC, emilyb93 commented on __tests__/app.test.js
> +});
I would prefer this be a 200 and just send an empty array back instead. This will make more sense on the front end, but it means less error handling on the front end where we can just loop through the array of comments, if theres an empty array then our code doesnt break, we just wont see anything on screen

2022-11-18 11:20 UTC, emilyb93 commented on model/comments-by-review-id.model.js
> +      }
Like i said for your test, we want just an empty array if the article exists with no comments, but a 404 if it does not exist, you will have to change this error handling slightly to account for this and make a query to the article table also to filter out whether an empty array means the article exists or not

2022-11-18 11:20 UTC, emilyb93 requested changes
slight changes please :)

2022-11-18 16:16 UTC, merged